CREATE TABLE Facturas (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Concepto VARCHAR(255) NOT NULL,
	Fecha DATETIME NOT NULL,
	Monto FLOAT NOT NULL,
	Proveedor VARCHAR(255) NOT NULL
)
GO

SELECT * FROM Facturas