CREATE TABLE INVOICES (
    Id VARCHAR (100) NOT NULL,
    Invoice_Date DATE NOT NULL,
    Amount DECIMAL NOT NULL,
    PaymentMethod VARCHAR (100) NOT NULL,
    Payee VARCHAR (100) NOT NULL,
    Detail VARCHAR (4000) NOT NULL
);

SELECT * FROM INVOICES;