CREATE TABLE INVOICES (
    Id VARCHAR (100) NOT NULL,
    Invoice_Date TIMESTAMP NOT NULL,
    Amount DECIMAL NOT NULL,
    Payment_Method VARCHAR (100) NOT NULL,
    Payee VARCHAR (100) NOT NULL,
    Detail VARCHAR (4000) NOT NULL
);

ALTER TABLE INVOICES ADD CONSTRAINT PK_INVOICES_ID PRIMARY KEY (Id);

SELECT * FROM INVOICES;
--DROP TABLE INVOICES;

INSERT INTO INVOICES VALUES ('Factura_1', '2022-05-30 04:10:06', 0, 'Cash', 'EA', '');
UPDATE INVOICES SET Payment_Method = 'DebitCard';
UPDATE INVOICES SET id = '37227198-8f6c-42ba-9d7f-4d728c1b2b90' WHERE id = 'Factura_3';
